plugins {
    id 'base'
}

allprojects {
    group = 'ru.practicum.yakovlev'
    version = '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    pluginManager.withPlugin('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
    }
}
